#!/usr/bin/env sh

. /usr/lib/pacmatic--lib

docs()  # none : docs
{
    echo -e "Usage: `basename $0` -arg [packages]"
    echo -e "\nPacmatic is a pacman wrapper that takes care of menial but critial tasks."
    echo -e "\nThese include"
    echo -e "\tChecking the archlinux.org news"
    echo -e "\tReminding if it has been a while since the last sync"
    echo -e "\tReporting pacnew files"
    echo -e "\tEditing pacnew files"
    echo -e "\nThe following environment variables can be set"
    echo -e "\twarn_time=\"$warn_time\"  # (seconds)"
    echo -e "\trss_feed=\"$rss_feed\""
    echo -e "\tlog_file=\"$log_file\""
    echo -e "\tpacdiff_program=\"$pacdiff_program\""
    echo -e "\tpacman_program=\"$pacman_program\""
    echo -e "\tmail_list=\"$mail_list\""
    echo -e "\tpacman_log=\"$pacman_log\""
    echo -e ""
}

if [ $# -eq 0 ]; then
    docs
    exit
fi
current_time=`date +%s`
sync_time=`last_sync`
upgrade_time=`last_upgrade`

case "$1" in
    -Syu|-Su|-Suy|-Syyu|-Syuy|-Suyy|-S|-Sy|-Syy)
        # do not like this threading
        check_news &
        mail_summary
        wait
        echo "Recent ML chatter: $mail_counts"
        ;;
esac

case "$1" in
    -Syu|-Su|-Suy|-Syyu|-Syuy|-Suyy)
        #check_news
        ;;
    -S)
        #check_news
        if [ $(( $sync_time - $upgrade_time )) -gt $(( $warn_time )) ]; then
            echo -e "\nWarning: stale installation, rerun with '-Syu'\n"
        fi
    ;;
    -Sy|-Syy)
        #check_news
        if [ $(( $current_time - $upgrade_time )) -gt $(( $warn_time )) ]; then
            echo -e "\nWarning: stale installation, rerun with '-Syu'\n"
        fi
    ;;
esac

old_pc=`pacnew_count`
$pacman_program $*
exit_code=$?
exit_time=`date "+[%F %H:%M]"`
echo "$exit_time Exited with code $exit_code" >> "$pacman_log"
new_pc=`pacnew_count`
add_pc=$(( $new_pc - $old_pc ))

# this section is a little clumsy

if [ "$new_pc" = "0" ]; then
  echo "No pacnew files to update."
  exit 0
fi

case "$1" in
    -Syu|-Su|-S|-Sy)
    echo -en "\n$new_pc pacnew files found ($add_pc added).  Update files now? (Y/n) "
    read char
    if [ -z "$char" ]; then
        $pacdiff_program
    fi
    case "$char" in
        Y|y)
            $pacdiff_program
        ;;
        N|n)
            ;;
        *)
            ;;
    esac
    ;;
    *)
        ;;
esac
